"""
Typed data for the Milestone 39 action protocol: immutable candidates, the
closed Decision union the strict parser produces, and the typed failure
outcomes that same parser returns instead of raising.

Nothing here performs I/O, calls a model, or executes an action - these are
plain, frozen data shared between kernel/action_protocol/candidates.py,
prompt.py, and parser.py. Protocol version is fixed at 1 for the whole of
Milestone 39; there is no mechanism here for negotiating a different one.
"""

from dataclasses import dataclass
from enum import Enum

from kernel.tools.types import ActionRequest

PROTOCOL_VERSION = 1

# The largest number of ActionCandidate objects one CandidateResolution may
# ever hold, and the largest candidate_id enum a dynamic schema (see
# prompt.py) may ever contain. Milestone 39's conservative single-action
# resolver never produces more than one, but this is enforced generically
# rather than assumed, so a future resolver extension cannot silently
# exceed it.
MAX_CANDIDATES = 10

# Fixed, code-level limits shared by prompt.py (declared in the dynamic
# JSON schema's maxLength constraints) and parser.py (re-checked at parse
# time - the schema is a strong hint to the model, never the only line of
# defense). Not user- or config-configurable.
MAX_RESPONSE_CHARS = 4_000  # the whole raw model response, before parsing
MAX_FIELD_CHARS = 800  # any individual text field: response/question/reason/user_summary
MAX_CANDIDATE_ID_CHARS = 64
MAX_JSON_NESTING_DEPTH = 8


@dataclass(frozen=True)
class ActionCandidate:
    """One immutable, code-owned candidate action a request may resolve
    to (see kernel/action_protocol/candidates.py). `candidate_id` is an
    opaque, code-generated, request-local label ("candidate_1", ...) -
    never derived from `action_request.action` or `.resource_key`, and
    never something the model can influence. `action_request` is the
    exact kernel/tools/types.ActionRequest this candidate represents -
    reusing that existing type rather than duplicating an
    action-name-plus-resource-key shape. `user_summary` is generated by
    code from ActionRegistry metadata only - it must never contain a
    path, command, executable, script content, or secret."""

    candidate_id: str
    action_request: ActionRequest
    sensitive: bool
    user_summary: str


@dataclass(frozen=True)
class RespondDecision:
    protocol_version: int
    response: str


@dataclass(frozen=True)
class SelectCandidateDecision:
    """`candidate` is always the exact, immutable ActionCandidate object
    that was supplied to the parser for this request - never
    reconstructed from model output. See parser.py."""

    protocol_version: int
    candidate: ActionCandidate
    user_summary: str


@dataclass(frozen=True)
class RequestClarificationDecision:
    protocol_version: int
    question: str


@dataclass(frozen=True)
class CannotCompleteDecision:
    protocol_version: int
    reason: str


Decision = (
    RespondDecision
    | SelectCandidateDecision
    | RequestClarificationDecision
    | CannotCompleteDecision
)


class ParseErrorCode(Enum):
    """Typed protocol-parsing failure categories. Every one of these is a
    problem with the model's *output* (or, for INVALID_CANDIDATE_SET, with
    the candidate tuple a caller supplied to the parser) - never a
    provider-availability or timeout problem. Provider/timeout failures
    stay ordinary exceptions raised by the model layer (see
    kernel/models/ollama.py) and are the caller's responsibility to map to
    a safe message; they are never represented as a ParseErrorCode and
    never turned into a persisted task (persistence begins in
    Milestone 40)."""

    EMPTY_RESPONSE = "empty_response"
    RESPONSE_TOO_LARGE = "response_too_large"
    MALFORMED_JSON = "malformed_json"
    DUPLICATE_KEY = "duplicate_key"
    INVALID_CONSTANT = "invalid_constant"
    EXCESSIVE_NESTING = "excessive_nesting"
    SCHEMA_VALIDATION_FAILED = "schema_validation_failed"
    UNKNOWN_PROTOCOL_VERSION = "unknown_protocol_version"
    UNSUPPORTED_DECISION = "unsupported_decision"
    UNKNOWN_CANDIDATE = "unknown_candidate"
    INVALID_CANDIDATE_SET = "invalid_candidate_set"


@dataclass(frozen=True)
class ParseFailure:
    """A failed parse. `detail` is a short, fixed, human-readable phrase
    describing the failure category - it never contains, quotes, or
    echoes any part of the raw model response (see parser.py's "do not
    log raw model text" requirement)."""

    error: ParseErrorCode
    detail: str


@dataclass(frozen=True)
class ParseSuccess:
    decision: Decision


ParseResult = ParseSuccess | ParseFailure


@dataclass(frozen=True)
class CandidateResolution:
    """Result of kernel/action_protocol/candidates.py's deterministic
    Stage A resolution. Exactly one of two shapes:
      - deterministic_clarification is a RequestClarificationDecision and
        candidates is empty - Stage A recognized a supported single-action
        intent but its required target was absent, so Stage B (a model
        call) is skipped entirely for this request.
      - deterministic_clarification is None and candidates holds zero or
        more ActionCandidate objects (at most MAX_CANDIDATES) - Stage B is
        then called with exactly this candidate set.
    """

    candidates: tuple[ActionCandidate, ...]
    deterministic_clarification: RequestClarificationDecision | None

    def __post_init__(self):
        if self.deterministic_clarification is not None and self.candidates:
            raise ValueError(
                "CandidateResolution: deterministic_clarification and "
                "non-empty candidates are mutually exclusive"
            )
        if len(self.candidates) > MAX_CANDIDATES:
            raise ValueError(
                f"CandidateResolution: candidates exceeds MAX_CANDIDATES ({MAX_CANDIDATES})"
            )
