"""
Typed data, the closed state/transition table, code-only ID generation,
and the error taxonomy for kernel/employee_tasks/ (Milestone 40).

Nothing here performs I/O - these are plain, frozen data and pure
functions shared by db.py and repository.py, matching
kernel/knowledge_base/types.py's own convention. task_id/display_id
generation is code-only and deterministic-or-random exactly as documented
on each function below; the model never generates either.
"""

import json
import uuid
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from enum import Enum

SCHEMA_VERSION = 7
PROTOCOL_VERSION = 1

# Fixed, code-level bounds on every externally supplied text field. Not
# configurable - see kernel/employee_tasks/repository.py's validators.
MIN_REQUEST_TEXT_CHARS = 1
MAX_REQUEST_TEXT_CHARS = 4096
MIN_SOURCE_CHARS = 1
MAX_SOURCE_CHARS = 64
MAX_METADATA_JSON_CHARS = 4096
MAX_DEDUP_KEY_CHARS = 128
MAX_FAILURE_CODE_CHARS = 64
MAX_FAILURE_SUMMARY_CHARS = 512
MAX_REASON_CODE_CHARS = 64
MAX_SAFE_SUMMARY_CHARS = 512
# Schema version 2 (Milestone 41 P2): bound on the opaque, code-generated
# plan_json column - kernel/task_planner/serialization.py:serialize_plan()
# enforces this same bound before ever returning a string for persistence
# (imported from here, the single source of truth - see that module's own
# docstring). Sized with headroom over an 8-step plan's computed worst case
# (~7KB of bounded text fields plus JSON syntax overhead). This layer only
# ever validates plan_json for size/well-formedness, exactly like
# metadata_json - it never inspects a plan's structure or acts on its
# content.
MAX_PLAN_JSON_CHARS = 16_384
# Schema version 3 (Milestone 42 P1): bound on the opaque, per-step
# result_json column in task_step_progress - the durable, safe-to-relay
# observation a future kernel.task_execution writes once a step reaches a
# terminal status. Sized the same as metadata_json: a bounded summary/
# failure description, never raw tool output. This layer only ever
# validates result_json for size/well-formedness, exactly like
# metadata_json/plan_json - it never inspects its structure or acts on its
# content.
MAX_STEP_RESULT_JSON_CHARS = 4096
# Schema version 4 (Milestone 42 P2): bounds on task_pending_confirmation's
# two code-supplied identity columns. Both values always originate from an
# already-validated, current-registry-checked PlanStep (never directly from
# user/model text) by the time kernel.task_execution calls
# propose_confirmation() - these bounds are defense in depth, matching this
# module's "the caller already validated it, but never trust that alone"
# doctrine, not a real-world size expectation (every actual ActionRegistry
# action/resource-key name today is well under 32 characters).
MAX_CONFIRMATION_ACTION_NAME_CHARS = 128
MAX_CONFIRMATION_RESOURCE_KEY_CHARS = 128
# Bound on the confirmation_id an approve/deny caller supplies BACK to this
# layer (consume_confirmation_and_claim_step()/deny_confirmation()/
# fail_pending_confirmation()) - unlike action_name/resource_key above,
# this value is never generated by this call's own caller; it is
# code-generated once at propose_confirmation() time (see generate_task_id())
# and handed back by whatever external caller is approving/denying later
# (Milestone 46's eventual WhatsApp reply routing, in a future milestone -
# not this one). Sized with generous headroom over a UUID7 string's fixed
# 36 characters - this bound intentionally does NOT require confirmation_id
# to look like a UUID (see generate_task_id()'s own "opaque, code-generated"
# framing): exact opaque-token matching is what actually authorizes
# anything, never a specific string shape.
MAX_CONFIRMATION_ID_CHARS = 128

# Schema version 5 (Milestone 47 P1): bounds for task_lifecycle_outbox.
# MAX_LIFECYCLE_CHANNEL_CHARS mirrors MAX_SOURCE_CHARS exactly - channel is
# always derived verbatim from the owning task's own `source` column (see
# TaskRepository's own module docstring on the outbox atomicity invariant),
# never a second, independently-bounded value.
MAX_LIFECYCLE_CHANNEL_CHARS = MAX_SOURCE_CHARS
# Generous headroom over a serialized ConfirmationRequiredPayload (three
# fields, each already independently bounded to at most
# MAX_CONFIRMATION_ACTION_NAME_CHARS/MAX_CONFIRMATION_RESOURCE_KEY_CHARS/
# MAX_CONFIRMATION_ID_CHARS - 128 characters apiece) plus JSON syntax
# overhead - the only event_kind that ever has a non-NULL payload_json (see
# LifecycleOutboxEvent's own docstring for why COMPLETED/FAILED/CANCELLED
# never need one).
MAX_LIFECYCLE_PAYLOAD_JSON_CHARS = 512

# Milestone 47 P1: the lifecycle-outbox delivery-retry backoff window -
# capped exponential, computed by compute_outbox_retry_delay_seconds()
# below. Deliberately simple (no attempt-count-specific schedule beyond a
# power-of-two cap) - this is a personal-scale, infrequently-restarted
# system, not a high-volume messaging platform; a fixed cadence bounded
# between these two values is sufficient to avoid both a tight retry loop
# and an indefinitely-growing delay.
OUTBOX_BASE_DELAY_SECONDS = 60.0
OUTBOX_MAX_DELAY_SECONDS = 3600.0

DISPLAY_ID_PREFIX = "TASK-"
DISPLAY_ID_LENGTH = 8
# Bounded retry count for the extremely unlikely case that a freshly
# generated display_id (or, vanishingly less likely, task_id) collides
# with an existing row's UNIQUE constraint - see generate_display_id()'s
# docstring and TaskRepository.create_task().
MAX_DISPLAY_ID_ATTEMPTS = 5

MIN_LIST_LIMIT = 1
MAX_LIST_LIMIT = 100
DEFAULT_LIST_LIMIT = 20

# Crockford-style uppercase alphabet with visually ambiguous characters
# (0, 1, I, L, O) removed - safe to read aloud or copy from a WhatsApp
# message without misreading a character.
_DISPLAY_ID_ALPHABET = "23456789ABCDEFGHJKMNPQRSTUVWXYZ"


class TaskState(str, Enum):
    """The closed set of lifecycle states a persisted task may be in.
    Inherits str so a TaskState member compares equal to, and can be
    stored/read as, its plain string value - no separate serialization
    step is needed at the SQLite boundary."""

    CREATED = "created"
    PLANNING = "planning"
    READY = "ready"
    RUNNING = "running"
    WAITING_FOR_CONFIRMATION = "waiting_for_confirmation"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


# Terminal states never accept a further transition, including back to
# themselves or to another active state - enforced both here (in
# TaskRepository, before any SQL runs) and structurally, since none of
# them appear as a key with a non-empty value in ALLOWED_TRANSITIONS.
TERMINAL_STATES = frozenset({TaskState.COMPLETED, TaskState.FAILED, TaskState.CANCELLED})

# The exact, closed transition table. Cancellation is allowed from every
# non-terminal state - nothing in the current roadmap needs an
# uncancellable working state. No other states or edges exist.
#
# PLANNING -> CREATED (Milestone 47 P3) is the one exception to "forward
# progress only": restart/crash reconciliation for a task stranded
# PLANNING - planning is model-only (no external side effect), so
# abandoning an interrupted model call and re-entering CREATED for a
# fresh planning attempt is safe. Never used outside restart
# reconciliation (see TaskRepository.transition_task()'s own
# RESTART_PLANNING_INTERRUPTED_REASON_CODE, the sole caller-supplied
# reason this edge is ever taken with).
ALLOWED_TRANSITIONS: dict[TaskState, frozenset[TaskState]] = {
    TaskState.CREATED: frozenset({TaskState.PLANNING, TaskState.CANCELLED, TaskState.FAILED}),
    TaskState.PLANNING: frozenset(
        {TaskState.READY, TaskState.CANCELLED, TaskState.FAILED, TaskState.CREATED}
    ),
    TaskState.READY: frozenset({TaskState.RUNNING, TaskState.CANCELLED, TaskState.FAILED}),
    TaskState.RUNNING: frozenset(
        {
            TaskState.WAITING_FOR_CONFIRMATION,
            TaskState.COMPLETED,
            TaskState.FAILED,
            TaskState.CANCELLED,
        }
    ),
    TaskState.WAITING_FOR_CONFIRMATION: frozenset(
        {TaskState.RUNNING, TaskState.CANCELLED, TaskState.FAILED}
    ),
    TaskState.COMPLETED: frozenset(),
    TaskState.FAILED: frozenset(),
    TaskState.CANCELLED: frozenset(),
}


class StepStatus(str, Enum):
    """The closed set of durable statuses one plan step's progress row may
    hold (Milestone 42 P1). Inherits str for the same reason
    TaskState does - a member compares equal to, and can be stored/read
    as, its plain string value.

    There is deliberately no NOT_STARTED member: the absence of a
    task_step_progress row for a given (task_id, step_position) IS
    "not started" - see TaskRepository.claim_step()/get_step_progress().
    Persisting an explicit not_started row for every step of every plan
    would be redundant data with no independent meaning."""

    IN_PROGRESS = "in_progress"
    SUCCEEDED = "succeeded"
    FAILED = "failed"


# Write-once terminal step statuses (SUCCEEDED, FAILED) are enforced
# directly by TaskRepository._finalize_step()'s conditional UPDATE
# (... WHERE status = 'in_progress') - unlike TERMINAL_STATES, no separate
# frozenset constant is declared here, since nothing in this package needs
# to test "is this status terminal" as a standalone question; the one
# place that matters (_finalize_step()) already expresses the equivalent
# and sufficient condition ("is this status still in_progress") directly
# in SQL.


class TaskStorageError(Exception):
    """Base class for every error kernel/employee_tasks/ raises
    deliberately (as opposed to letting an unrelated exception escape).
    Never carries a SQL fragment, stack trace, or raw driver exception
    text meant for a caller to inspect via str() - callers select a
    fixed, safe message by exception *type*, matching
    kernel/knowledge_base/types.py's own convention."""


class TaskNotFoundError(TaskStorageError):
    """No task exists with the given task_id or display_id."""


class InvalidTransitionError(TaskStorageError):
    """The requested expected_state -> new_state pair is not in
    ALLOWED_TRANSITIONS, new_state is not a recognized TaskState, or the
    task's actual current state no longer matches the caller's
    expected_state (a stale write, including one lost to a concurrent
    writer). Neither the tasks row nor the journal is ever modified when
    this is raised."""


class TaskAlreadyTerminalError(TaskStorageError):
    """The task's actual current state is already terminal
    (completed/failed/cancelled). Distinct from InvalidTransitionError so
    a caller can tell "you tried to skip/reverse a step" apart from "this
    task is already done and cannot be touched again"."""


class DuplicateTaskError(TaskStorageError):
    """create_task() was called with a dedup_key that already exists."""


class TaskStorageUnavailableError(TaskStorageError):
    """The task database file or its containing directory could not be
    opened, created, initialized, or written to (including a write lock
    that could not be acquired within the busy timeout)."""


class TaskStorageCorruptError(TaskStorageError):
    """The database's persisted content is not what this code itself
    ever writes - either PRAGMA integrity_check reported an actual
    inconsistency in the database file (see db.py's check_integrity()),
    or (Milestone 42 P2) a persisted, code-generated timestamp column
    (e.g. task_pending_confirmation.expires_at) failed to parse back as a
    timezone-aware datetime (see parse_task_timestamp() below) - both are
    the same underlying concern: this layer's own prior write does not
    match what this layer expects to read back. Distinct from a schema
    version mismatch (TaskSchemaIncompatibleError), which is a perfectly
    readable file written by, or intended for, a different schema
    version."""


class TaskSchemaIncompatibleError(TaskStorageError):
    """The database's schema_meta.schema_version does not match the
    version this code expects."""


class TaskInputTooLargeError(TaskStorageError):
    """An externally supplied field violates this layer's bounded-input
    contract: the wrong type, too short, too long, or containing an
    embedded NUL byte - or, for metadata_json specifically, not
    syntactically valid JSON text. Named for the most common case (an
    oversized field) but covers the whole bounded-input contract, so the
    error taxonomy stays closed rather than growing one class per
    validation rule."""


class LifecycleEventPayloadError(TaskStorageError):
    """A task_lifecycle_outbox event's payload_json (Milestone 47 P1)
    either could not be serialized within MAX_LIFECYCLE_PAYLOAD_JSON_CHARS
    at write time, or - a read-time defense-in-depth check, never expected
    to fire against anything this layer itself ever wrote - could not be
    deserialized back into the expected ConfirmationRequiredPayload shape.
    Every field serialize_confirmation_required_payload() ever writes is
    already independently bounded by its own caller-side validation
    (MAX_CONFIRMATION_ACTION_NAME_CHARS/MAX_CONFIRMATION_RESOURCE_KEY_CHARS/
    MAX_CONFIRMATION_ID_CHARS), so this should be structurally unreachable
    in practice - but is never assumed away, matching this package's own
    "the caller already validated it, but never trust that alone"
    doctrine."""


class StepAlreadyClaimedError(TaskStorageError):
    """TaskRepository.claim_step() targeted a (task_id, step_position)
    pair that already has a task_step_progress row - whatever its status.
    A step may be claimed exactly once: the underlying INSERT relies on
    the table's (task_id, step_position) PRIMARY KEY to guarantee that,
    of any number of concurrent callers claiming the same step, exactly
    one succeeds and every other one gets this error. Never retried
    automatically - see kernel/task_execution/ (Milestone 42) for the
    fail-closed policy this supports."""


class StepNotInProgressError(TaskStorageError):
    """TaskRepository.mark_step_succeeded()/mark_step_failed() was called
    for a (task_id, step_position) that either has no claimed row at all,
    or whose row is no longer in_progress (already succeeded or failed).
    Terminal step status is write-once: neither a succeeded nor a failed
    row can ever move to any other status, and a terminal row's
    result/failure fields can never be overwritten - both are enforced by
    this same error, raised from the same conditional-UPDATE guard."""


class NoPendingConfirmationError(TaskStorageError):
    """No task_pending_confirmation row exists for the given task_id -
    raised by consume_confirmation_and_claim_step()/deny_confirmation()
    when there is nothing to approve/deny (including a second attempt
    after the first already consumed or denied it)."""


class ConfirmationMismatchError(TaskStorageError):
    """The confirmation identity supplied to
    consume_confirmation_and_claim_step()/deny_confirmation() does not
    EXACTLY match the currently pending task_pending_confirmation row
    (confirmation_id and, for approval, step_position/action_name/
    resource_key too). Never partially honored - a mismatch on any single
    field fails the whole call closed, exactly like a stale or replayed
    confirmation_id must never be treated as authorizing a different,
    newer pending confirmation for the same task."""


class ConfirmationExpiredError(TaskStorageError):
    """The pending confirmation matched exactly, but its expires_at has
    already passed. consume_confirmation_and_claim_step() raises this
    without mutating anything - the caller (kernel/task_execution/) is
    expected to call fail_pending_confirmation() as a separate, explicit
    step to actually transition the task to failed; this error alone
    never does that itself, so an attempted approve never has a silent
    side effect beyond reporting why it did not succeed."""


@dataclass(frozen=True)
class TaskRecord:
    """One persisted task's current row. `metadata_json` and `plan_json`
    are both stored and returned as opaque, size-capped JSON strings -
    this layer never parses their keys or acts on their contents (see
    repository.py). `plan_json` is None until a validated plan has been
    persisted (schema version 2, Milestone 41 P2) - only
    TaskRepository.persist_plan_and_ready() ever sets it, exactly once,
    atomically with the planning -> ready transition; there is no general
    update API for it."""

    task_id: str
    display_id: str
    state: TaskState
    request_text: str
    source: str
    dedup_key: str | None
    created_at: str
    updated_at: str
    started_at: str | None
    completed_at: str | None
    failure_code: str | None
    failure_summary: str | None
    metadata_json: str
    protocol_version: int
    version: int
    plan_json: str | None = None
    # Milestone 47 P3 (adversarial-review correction): durable backoff
    # state for find_one_recoverable_task()'s own due-ordered pickup -
    # mirrors task_pending_confirmation's decision_attempt_count/
    # decision_next_attempt_at (Milestone 47 P2) exactly, for the
    # identical reason: without it, one recoverable task whose recovery
    # dispatch keeps raising (without ever transitioning the task out of
    # its recoverable state) permanently starves every task created after
    # it, since a plain oldest-first scan always re-selects the same row.
    # recovery_attempt_count starts at 0 and recovery_next_attempt_at
    # starts at NULL (== "never deferred, immediately eligible") for
    # every task - see TaskRepository.defer_task_recovery_retry() for how
    # they change after a failed recovery dispatch.
    recovery_attempt_count: int = 0
    recovery_next_attempt_at: str | None = None


@dataclass(frozen=True)
class TaskTransition:
    """One append-only journal row. `from_state` is None only for the
    synthetic creation event (see TaskRepository.create_task) - every
    later transition always has both a from_state and a to_state."""

    transition_id: int
    task_id: str
    from_state: TaskState | None
    to_state: TaskState
    timestamp: str
    reason_code: str | None
    safe_summary: str | None
    task_version: int


@dataclass(frozen=True)
class TaskStepProgress:
    """One durable task_step_progress row (Milestone 42 P1) - the
    smallest durable record of one plan step's execution progress.
    `step_position` matches kernel.task_planner.types.PlanStep.position
    exactly, but this layer never imports or inspects PlanStep/TaskPlan -
    step_position is treated as an opaque, positive, code-supplied integer,
    exactly like plan_json's content is opaque to this package (see
    kernel/employee_tasks/__init__.py's own scope statement).

    There is no row for a step that has not been claimed yet - see
    StepStatus's own docstring. `result_json` is populated only once the
    step reaches a terminal status (`succeeded`, always; `failed`,
    optionally) and is treated exactly as opaquely as plan_json/
    metadata_json: this layer validates only that it parses as JSON and
    stays within its size bound. `task_version` is the `tasks.version`
    value observed at claim time - a lightweight forensic snapshot, not a
    concurrency mechanism in its own right (the (task_id, step_position)
    PRIMARY KEY is what actually makes claim_step() atomic)."""

    task_id: str
    step_position: int
    status: StepStatus
    started_at: str
    completed_at: str | None
    result_json: str | None
    failure_code: str | None
    failure_summary: str | None
    task_version: int


class ConfirmationDecision(str, Enum):
    """The closed set of durable decisions a CONFIRM/REJECT command may
    record against a pending confirmation (Milestone 47 P2) - mirrors
    TaskState/StepStatus/LifecycleEventKind's own "inherits str" convention
    so a member compares equal to, and can be stored/read as, its plain
    string value. Exactly the two values
    task_pending_confirmation.decision's own schema-level CHECK constraint
    accepts (kernel/employee_tasks/db.py) - no other decision string is
    ever valid, matching this module's own "close the set in SQL too, not
    just in the enum" discipline (see _STEP_STATUS_LIST_SQL's own comment
    in db.py). This is the single, kernel-owned representation - never
    duplicated by interfaces/whatsapp/task_control.py, which imports this
    exact enum rather than defining its own equivalent."""

    CONFIRM = "confirm"
    REJECT = "reject"


class ConfirmationDecisionOutcome(str, Enum):
    """The closed set of outcomes TaskRepository.record_confirmation_decision()
    (Milestone 47 P2) may return - never a free-form string, never an
    exception for any of these three ordinary, expected results (an
    exception remains reserved for a genuine storage failure, matching
    every other repository method's own convention).

    RECORDED: this call's decision durably won - it, and only it, is now
    task_pending_confirmation.decision for this confirmation_id, AND a
    matching task_confirmation_ingress_receipts row now durably remembers
    this exact provider message as the one that won (see
    TaskRepository.record_confirmation_decision()'s own docstring for the
    atomicity of that pairing).
    ALREADY_DECIDED: a decision (whether this same one or the opposite one)
    was already durably recorded before this call ever reached the
    transaction - first-decision-wins, and this call never overwrote it.
    DUPLICATE_INGRESS (Milestone 47 P2 adversarial-review correction): this
    EXACT provider message was already the one that durably won a decision
    - detected via task_confirmation_ingress_receipts, which survives even
    after task_pending_confirmation's own row is later consumed/deleted.
    Distinct from ALREADY_DECIDED: ALREADY_DECIDED means "some decision for
    this confirmation_id already exists, but not necessarily from this
    exact provider message"; DUPLICATE_INGRESS means "this exact provider
    message itself already won, at any point in the past, even long after
    the pending row is gone" - the crash-safe, restart-surviving transport-
    redelivery answer NOT_ELIGIBLE could never give.
    NOT_ELIGIBLE: no durable decision was written, for any reason -
    confirmation_id does not resolve, the owning task's source does not
    match, the owning task is no longer WAITING_FOR_CONFIRMATION, or the
    pending row is otherwise gone. Deliberately as unspecific as
    get_task_by_pending_confirmation_id()'s own None return: which of
    these actually happened is never distinguishable from the outcome
    alone, so a wrong-source or expired-token attempt discloses nothing
    about which case occurred."""

    RECORDED = "recorded"
    ALREADY_DECIDED = "already_decided"
    DUPLICATE_INGRESS = "duplicate_ingress"
    NOT_ELIGIBLE = "not_eligible"


@dataclass(frozen=True)
class PendingTaskConfirmation:
    """One durable task_pending_confirmation row (Milestone 42 P2) - a
    task-scoped, durable pending confirmation, wholly independent of
    kernel/tools/confirmation.py's in-memory, single-slot ConfirmationStore
    (which remains untouched and keeps serving the existing ad hoc
    `/task ...` command path).

    `task_id` is the PRIMARY KEY: the architecture guarantees at most one
    pending confirmation per task, since execution is strictly sequential
    (a task can only be RUNNING one step's worth of work, or
    WAITING_FOR_CONFIRMATION for exactly one proposed step, at a time).
    `confirmation_id` is a separate, code-generated, single-use identity
    token - NOT the same value as task_id - because task_id alone cannot
    distinguish "the confirmation currently pending" from "a different,
    later confirmation this task will eventually propose after this one
    is resolved": approval/denial must match confirmation_id exactly, so a
    stale or replayed confirmation_id can never be mistaken for a newer,
    unrelated proposal. `step_position`/`action_name`/`resource_key`
    identify EXACTLY which persisted plan step/action/resource was
    proposed - snapshotted at propose time, never re-derived later.

    THREAT BOUNDARY (Milestone 42 P2 correction): approve_task_confirmation()
    (kernel/task_execution/service.py) re-binds this row's step_position to
    the immutable persisted TaskPlan and verifies action_name/resource_key
    match the resolved PlanStep exactly - this defeats a partial tamper
    (any ONE of these three fields changed in isolation, whether by an
    application bug, a race, or partial/corrupt mutation) by making the
    mismatch detectable. It does NOT, and is not intended to, defeat a
    coordinated rewrite by an attacker with arbitrary direct SQLite write
    access who changes ALL THREE fields together to exactly describe a
    DIFFERENT, currently-valid ACTION step already present in the SAME
    persisted plan - the database holds no independent, tamper-evident
    record of the original proposal to detect that specific rewrite
    against. This is a deliberate scope boundary, not an oversight: M42's
    threat model is stale/corrupt/inconsistent persisted state,
    application-level races, accidental partial mutation, replay, and
    unauthorized substitution by models or runtime code - never
    cryptographic tamper-resistance against an attacker who already has
    arbitrary write access to this process's own SQLite file (an
    attacker at that privilege level could equally rewrite tasks.plan_json
    itself, or any other row in this database). Defending against that
    specific threat would require an independent trust boundary (e.g. an
    authenticated/signed proposal record, or storage this process does not
    itself have unrestricted write access to) that no part of this
    codebase's existing threat model calls for today.

    `decision`/`decided_at` (Milestone 47 P2): durable confirmation-decision
    authority - see TaskRepository.record_confirmation_decision()'s own
    docstring for the exact atomic eligibility/first-decision-wins
    contract. Both are None until a decision has been durably recorded;
    `decision` is never any value other than a ConfirmationDecision member
    once non-None, matching the schema's own CHECK constraint. This row
    (and its decision, if any) is deleted, atomically, by whichever of
    consume_confirmation_and_claim_step()/deny_confirmation()/
    fail_pending_confirmation() actually consumes it - there is no separate
    durable "decision history" once that happens; the task_transitions
    journal remains the sole durable task-state history (a SEPARATE,
    independent durable record - task_confirmation_ingress_receipts -
    remembers only which provider message won, specifically so it can
    outlive this row's own deletion; see that table's own rationale on
    TaskRepository.record_confirmation_decision()).

    `decision_attempt_count`/`decision_next_attempt_at` (Milestone 47 P2
    adversarial-review correction): the SAME small, bounded, capped-
    exponential retry-scheduling shape task_lifecycle_outbox's own
    attempt_count/next_attempt_at already established for P1, applied here
    so one durable decision that repeatedly fails to be dispatched (before
    it is ever consumed) can never permanently starve every later durable
    decision behind it in find_recoverable_confirmation_decision()'s own
    due-ordered queue. Both are meaningless (0 / None) until a decision
    exists; once RECORDED, decision_next_attempt_at starts equal to
    decided_at (immediately due) and only ever moves forward, exactly like
    the outbox's own next_attempt_at never moves backward."""

    task_id: str
    confirmation_id: str
    step_position: int
    action_name: str
    resource_key: str | None
    created_at: str
    expires_at: str
    decision: ConfirmationDecision | None = None
    decided_at: str | None = None
    decision_attempt_count: int = 0
    decision_next_attempt_at: str | None = None


class LifecycleEventKind(str, Enum):
    """The closed set of durable lifecycle-outbox event kinds (Milestone
    47 P1) - mirrors TaskState/StepStatus's own "inherits str" convention.
    Exactly the four target states TaskRepository's own transition-producing
    methods ever treat as externally notification-worthy (see
    TaskRepository's own module docstring for the exact atomicity
    invariant and the four call sites that create one of these). No other
    event_kind string is ever accepted - db.py's own CHECK constraint
    closes this set at the schema level too, not merely in this enum."""

    CONFIRMATION_REQUIRED = "confirmation_required"
    TASK_COMPLETED = "task_completed"
    TASK_FAILED = "task_failed"
    TASK_CANCELLED = "task_cancelled"


@dataclass(frozen=True)
class LifecycleOutboxEvent:
    """One durable, at-least-once lifecycle-notification obligation
    (Milestone 47 P1) - created atomically, in the SAME SQLite transaction,
    by whichever TaskRepository method produces the corresponding
    deliverable task_transitions row; see that module's own docstring for
    the exact invariant ("if the lifecycle transition commits, the
    corresponding required lifecycle event exists - always, never later,
    never separately").

    `channel` is always exactly the owning task's own `source` column
    (task.source == "whatsapp" -> channel == "whatsapp") - never a second,
    independently-set value, and never model-selected. A delivery/recovery
    loop for one channel MUST filter on this column and must never consume
    a different channel's event; this table never stores a recipient of
    any kind - recipient authority always remains the CURRENT
    configuration of whichever interface owns `channel`, resolved fresh at
    send time, never persisted here.

    `payload_json` is populated only for CONFIRMATION_REQUIRED (see
    ConfirmationRequiredPayload's own docstring for why) and is always
    None for TASK_COMPLETED/TASK_FAILED/TASK_CANCELLED: every field their
    eventual message needs is already durably, permanently immutable on
    the task/step-progress rows themselves the instant a terminal
    transition commits (terminal states have no outgoing edges - see
    ALLOWED_TRANSITIONS), so re-deriving from current state at delivery
    time is provably safe for those three kinds, unlike
    CONFIRMATION_REQUIRED's own pending-row source data, which can
    legitimately be deleted and replaced by a later, different
    confirmation round while the task is still non-terminal.

    `transition_id` correlates this event to EXACTLY the one
    task_transitions row that created the obligation (UNIQUE at the schema
    level - see db.py) - this is what makes duplicate event creation for
    one transition structurally impossible, not merely conventionally
    avoided. `attempt_count`/`next_attempt_at` implement a small, bounded,
    capped-exponential retry schedule (see
    compute_outbox_retry_delay_seconds() below) - never unbounded, never
    a tight loop, and never storing a raw provider error/exception text."""

    event_id: str
    task_id: str
    transition_id: int
    channel: str
    event_kind: LifecycleEventKind
    payload_json: str | None
    created_at: str
    delivered_at: str | None
    attempt_count: int
    next_attempt_at: str


@dataclass(frozen=True)
class ConfirmationRequiredPayload:
    """The immutable, structured payload captured atomically inside
    TaskRepository.propose_confirmation()'s own transaction (Milestone 47
    P1) - never rendered WhatsApp (or any other interface's) wording
    itself, only the same three already-bounded, non-secret identifiers
    task_pending_confirmation itself already carries. Rendering the actual
    outbound text from this payload is the receiving interface's own job
    (see interfaces/whatsapp/task_control.py), exactly like it already is
    for a live, not-yet-resolved PendingTaskConfirmation row - this
    dataclass is deliberately duck-type-compatible with that one (same
    three field names) so a caller's own formatter can accept either
    without caring which one it was handed."""

    confirmation_id: str
    action_name: str
    resource_key: str | None


def serialize_confirmation_required_payload(payload: ConfirmationRequiredPayload) -> str:
    """Deterministic, canonical JSON serialization (sorted keys, compact
    separators - matching kernel.task_execution.observation's own
    serialize_observation() discipline). Raises LifecycleEventPayloadError
    if the result would exceed MAX_LIFECYCLE_PAYLOAD_JSON_CHARS; never
    truncates. Should be unreachable in practice given every field's own
    independent bound, but is real defense in depth, not assumed away."""

    data = {
        "confirmation_id": payload.confirmation_id,
        "action_name": payload.action_name,
        "resource_key": payload.resource_key,
    }
    serialized = json.dumps(data, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
    if len(serialized) > MAX_LIFECYCLE_PAYLOAD_JSON_CHARS:
        raise LifecycleEventPayloadError(
            f"serialized confirmation_required payload exceeds "
            f"MAX_LIFECYCLE_PAYLOAD_JSON_CHARS ({MAX_LIFECYCLE_PAYLOAD_JSON_CHARS})"
        )
    return serialized


# Milestone 47 P1 adversarial-review correction: the exact, closed set of
# top-level keys a durable confirmation_required payload may ever have -
# not one more, not one fewer. Checked via set equality, not merely
# presence, so an extra/unexpected key is rejected exactly like a missing
# one - both are "this durable row does not match the shape this layer
# itself ever wrote," and both fail the same way.
_CONFIRMATION_REQUIRED_PAYLOAD_KEYS = frozenset({"confirmation_id", "action_name", "resource_key"})


def _validate_deserialized_payload_str(value, field_name: str, min_len: int, max_len: int) -> str:
    """A small, LOCAL validator for deserialize_confirmation_required_payload()
    below - deliberately NOT kernel.employee_tasks.repository's own
    _validate_bounded_text(): repository.py already imports FROM this
    module, so importing back from repository.py here would be circular.
    Reuses the SAME bound constants repository.py's own write-path
    validators use (MAX_CONFIRMATION_ID_CHARS/
    MAX_CONFIRMATION_ACTION_NAME_CHARS/MAX_CONFIRMATION_RESOURCE_KEY_CHARS),
    so the two independently-implemented checks can never silently drift
    apart on the NUMBERS, even though the checking LOGIC is necessarily
    duplicated in shape given the layering. Raises LifecycleEventPayloadError
    directly, never TaskInputTooLargeError - this function exists solely to
    serve this one deserialization boundary's own single exception
    contract. Never includes the offending value in its own message - only
    the field name and a fixed, generic description, so a corrupted
    durable payload's own content is never echoed back through an
    exception."""

    if not isinstance(value, str):
        raise LifecycleEventPayloadError(f"{field_name} must be a string")
    if "\x00" in value:
        raise LifecycleEventPayloadError(f"{field_name} must not contain a NUL character")
    if not (min_len <= len(value) <= max_len):
        raise LifecycleEventPayloadError(
            f"{field_name} must be between {min_len} and {max_len} characters"
        )
    return value


def deserialize_confirmation_required_payload(raw: str) -> ConfirmationRequiredPayload:
    """The inverse of serialize_confirmation_required_payload() - a
    genuinely closed, bounded, type-checked schema, not merely a
    structural/presence check. Every malformed-input path raises only
    LifecycleEventPayloadError, never leaking the raw payload or any
    offending value in its own message, so a caller reading a durably-
    corrupted row back can always fail safely rather than crash or
    silently accept unvalidated data:

      - the raw string itself is bounded to MAX_LIFECYCLE_PAYLOAD_JSON_CHARS
        BEFORE json.loads() is ever called, so an arbitrarily oversized
        corrupted row is never even parsed;
      - invalid JSON syntax;
      - a non-object top level;
      - a key set that is not EXACTLY {confirmation_id, action_name,
        resource_key} - an extra key is rejected exactly like a missing
        one (see _CONFIRMATION_REQUIRED_PAYLOAD_KEYS's own comment);
      - confirmation_id/action_name: anything other than a non-empty,
        NUL-free string within the SAME bound
        (MAX_CONFIRMATION_ID_CHARS/MAX_CONFIRMATION_ACTION_NAME_CHARS) the
        write path already enforces - never coerced via str(value), a
        wrong-typed value (int/list/dict/bool/None) is rejected outright;
      - resource_key: anything other than None, or a non-empty, NUL-free
        string within MAX_CONFIRMATION_RESOURCE_KEY_CHARS - matching
        PendingTaskConfirmation/propose_confirmation()'s own "None means
        no resource, never an empty-string placeholder" semantics exactly."""

    if not isinstance(raw, str) or len(raw) > MAX_LIFECYCLE_PAYLOAD_JSON_CHARS:
        raise LifecycleEventPayloadError(
            f"payload exceeds MAX_LIFECYCLE_PAYLOAD_JSON_CHARS ({MAX_LIFECYCLE_PAYLOAD_JSON_CHARS})"
        )

    try:
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise LifecycleEventPayloadError("payload is not valid JSON") from exc

    if not isinstance(data, dict):
        raise LifecycleEventPayloadError("payload is not a JSON object")

    if set(data.keys()) != _CONFIRMATION_REQUIRED_PAYLOAD_KEYS:
        raise LifecycleEventPayloadError(
            "payload does not have exactly the expected confirmation_required keys"
        )

    confirmation_id = _validate_deserialized_payload_str(
        data["confirmation_id"], "confirmation_id", 1, MAX_CONFIRMATION_ID_CHARS
    )
    action_name = _validate_deserialized_payload_str(
        data["action_name"], "action_name", 1, MAX_CONFIRMATION_ACTION_NAME_CHARS
    )
    resource_key_raw = data["resource_key"]
    if resource_key_raw is None:
        resource_key = None
    else:
        resource_key = _validate_deserialized_payload_str(
            resource_key_raw, "resource_key", 1, MAX_CONFIRMATION_RESOURCE_KEY_CHARS
        )

    return ConfirmationRequiredPayload(
        confirmation_id=confirmation_id, action_name=action_name, resource_key=resource_key
    )


def compute_outbox_retry_delay_seconds(attempt_count: int) -> float:
    """Capped exponential backoff for a lifecycle-outbox delivery retry
    (Milestone 47 P1) - pure, deterministic, no I/O, no wall-clock read of
    its own. `attempt_count` is the NEW count after the failed attempt
    this delay is being computed for (call with 1 to get the delay before
    the second attempt). The EXPONENT itself is capped before 2**n is ever
    computed - never a literal unbounded exponentiation - so this stays
    cheap and safe no matter how large attempt_count ever grows; the
    result is then also capped at OUTBOX_MAX_DELAY_SECONDS regardless."""

    if attempt_count < 1:
        attempt_count = 1
    capped_exponent = min(attempt_count - 1, 10)  # 2**10 already saturates past OUTBOX_MAX_DELAY_SECONDS
    return min(OUTBOX_BASE_DELAY_SECONDS * (2 ** capped_exponent), OUTBOX_MAX_DELAY_SECONDS)


def parse_task_timestamp(value: str, field_name: str = "timestamp") -> datetime:
    """Parse a code-generated ISO-8601 timestamp this package itself wrote
    (e.g. PendingTaskConfirmation.expires_at) back into a real,
    timezone-aware datetime - for any chronological comparison (in
    particular an authorization-expiry decision - see
    TaskRepository.consume_confirmation_and_claim_step()), never a lexical
    string comparison. Two ISO-8601 strings sharing the exact same
    formatting convention usually happen to sort correctly as plain
    strings, but nothing here should ever depend on that coincidence
    holding for every representable instant - datetime.isoformat() omits
    the fractional-seconds component entirely when it is exactly zero,
    which is exactly the kind of formatting variation string comparison
    must not be trusted to handle correctly, security-relevant or not.

    A value that fails to parse, or parses as timezone-naive, is a
    storage/integrity concern - this package never itself writes such a
    value - so it fails closed as TaskStorageCorruptError, never silently
    treated as a valid (and in particular never as a "not yet expired")
    timestamp. Shared by kernel.employee_tasks.repository and
    kernel.task_execution.service so neither package maintains its own,
    possibly-drifting copy of this parsing/validation logic."""

    if not isinstance(value, str):
        raise TaskStorageCorruptError(f"{field_name} must be a string")
    try:
        parsed = datetime.fromisoformat(value)
    except ValueError as exc:
        raise TaskStorageCorruptError(f"{field_name} is not a valid ISO-8601 timestamp") from exc
    if parsed.tzinfo is None:
        raise TaskStorageCorruptError(f"{field_name} is not a timezone-aware timestamp")
    return parsed


def format_utc_timestamp(value: datetime) -> str:
    """Milestone 47 P1 adversarial-review correction: the ONE canonical,
    fixed-width, always-microsecond-precision UTC serialization used for
    task_lifecycle_outbox's own created_at/next_attempt_at columns - see
    TaskRepository.list_due_lifecycle_outbox_events()'s own docstring for
    the exact invariant this establishes (plain lexical SQL comparison
    provably, not merely coincidentally, equivalent to chronological
    comparison).

    Unlike datetime.isoformat()'s own default behavior - which OMITS the
    fractional-seconds component entirely when it is exactly zero,
    producing a SHORTER string for that one case (see
    parse_task_timestamp()'s own docstring for why that variable-width
    behavior is unsafe to compare lexically) - this ALWAYS includes
    exactly six fractional digits (`timespec="microseconds"`), so every
    value this function ever produces has the identical fixed structure:
    the well-known, provably-correct condition for "lexical order equals
    chronological order" over zero-padded, fixed-width date/time
    components. Always converts to UTC first (`.astimezone(timezone.utc)`)
    - never trusts or preserves a non-UTC offset, so this function alone
    is always safe to call on any genuinely timezone-aware datetime,
    regardless of its original offset; callers that must additionally
    REJECT a non-UTC input outright (rather than silently normalizing it)
    perform that check themselves before calling this function - see
    TaskRepository.mark_lifecycle_event_delivery_failed()'s own explicit
    UTC-only gate for exactly that stricter contract.

    Raises ValueError (matching datetime's own contract for this precise
    situation - never a custom exception type) if `value` is not
    timezone-aware; every caller in this codebase already has a real,
    timezone-aware datetime object in hand, never caller-supplied raw
    text, so this is a programming-contract check, not an external-input
    validation boundary."""

    if value.tzinfo is None:
        raise ValueError("value must be a timezone-aware datetime")
    return value.astimezone(timezone.utc).isoformat(timespec="microseconds")


def generate_task_id() -> str:
    """Code-generated, time-ordered (UUID7), globally-unique-enough-for-
    one-installation task identity. Never derived from, or influenced by,
    model output - see kernel/employee_tasks/__init__.py."""

    return str(uuid.uuid7())


def generate_display_id(task_id: str) -> str:
    """Deterministic short code derived from task_id's raw bytes - not an
    independent random draw, so there is nothing extra to generate,
    persist, or reconcile against task_id itself.

    Algorithm: interpret the UUID's 128 bits as one big-endian integer,
    then repeatedly divmod by len(_DISPLAY_ID_ALPHABET), taking
    DISPLAY_ID_LENGTH digits least-significant-first and reversing them
    at the end - i.e. this is exactly "encode the integer in base 31
    using this alphabet, keep the last 8 digits". Prefixed with
    DISPLAY_ID_PREFIX ("TASK-") for readability.

    This is a *lossy* projection of 128 bits down to 8 symbols from a
    31-character alphabet (~40 bits) - collisions between two different
    task_ids are possible in principle (roughly 1 in 31**8), which is
    exactly why TaskRepository.create_task() treats a display_id UNIQUE
    violation as a signal to retry with a fresh task_id/display_id pair
    (bounded by MAX_DISPLAY_ID_ATTEMPTS) rather than assuming this
    function is injective. Not a secret, and never used for
    authorization - see kernel/employee_tasks/__init__.py.
    """

    raw = uuid.UUID(task_id).bytes
    remaining = int.from_bytes(raw, "big")
    base = len(_DISPLAY_ID_ALPHABET)
    digits = []
    for _ in range(DISPLAY_ID_LENGTH):
        remaining, remainder = divmod(remaining, base)
        digits.append(_DISPLAY_ID_ALPHABET[remainder])
    return DISPLAY_ID_PREFIX + "".join(reversed(digits))
