"""
Typed data, the closed state/transition table, code-only ID generation,
and the error taxonomy for kernel/employee_tasks/ (Milestone 40).

Nothing here performs I/O - these are plain, frozen data and pure
functions shared by db.py and repository.py, matching
kernel/knowledge_base/types.py's own convention. task_id/display_id
generation is code-only and deterministic-or-random exactly as documented
on each function below; the model never generates either.
"""

import uuid
from dataclasses import dataclass
from datetime import datetime
from enum import Enum

SCHEMA_VERSION = 4
PROTOCOL_VERSION = 1

# Fixed, code-level bounds on every externally supplied text field. Not
# configurable - see kernel/employee_tasks/repository.py's validators.
MIN_REQUEST_TEXT_CHARS = 1
MAX_REQUEST_TEXT_CHARS = 4096
MIN_SOURCE_CHARS = 1
MAX_SOURCE_CHARS = 64
MAX_METADATA_JSON_CHARS = 4096
MAX_DEDUP_KEY_CHARS = 128
MAX_FAILURE_CODE_CHARS = 64
MAX_FAILURE_SUMMARY_CHARS = 512
MAX_REASON_CODE_CHARS = 64
MAX_SAFE_SUMMARY_CHARS = 512
# Schema version 2 (Milestone 41 P2): bound on the opaque, code-generated
# plan_json column - kernel/task_planner/serialization.py:serialize_plan()
# enforces this same bound before ever returning a string for persistence
# (imported from here, the single source of truth - see that module's own
# docstring). Sized with headroom over an 8-step plan's computed worst case
# (~7KB of bounded text fields plus JSON syntax overhead). This layer only
# ever validates plan_json for size/well-formedness, exactly like
# metadata_json - it never inspects a plan's structure or acts on its
# content.
MAX_PLAN_JSON_CHARS = 16_384
# Schema version 3 (Milestone 42 P1): bound on the opaque, per-step
# result_json column in task_step_progress - the durable, safe-to-relay
# observation a future kernel.task_execution writes once a step reaches a
# terminal status. Sized the same as metadata_json: a bounded summary/
# failure description, never raw tool output. This layer only ever
# validates result_json for size/well-formedness, exactly like
# metadata_json/plan_json - it never inspects its structure or acts on its
# content.
MAX_STEP_RESULT_JSON_CHARS = 4096
# Schema version 4 (Milestone 42 P2): bounds on task_pending_confirmation's
# two code-supplied identity columns. Both values always originate from an
# already-validated, current-registry-checked PlanStep (never directly from
# user/model text) by the time kernel.task_execution calls
# propose_confirmation() - these bounds are defense in depth, matching this
# module's "the caller already validated it, but never trust that alone"
# doctrine, not a real-world size expectation (every actual ActionRegistry
# action/resource-key name today is well under 32 characters).
MAX_CONFIRMATION_ACTION_NAME_CHARS = 128
MAX_CONFIRMATION_RESOURCE_KEY_CHARS = 128
# Bound on the confirmation_id an approve/deny caller supplies BACK to this
# layer (consume_confirmation_and_claim_step()/deny_confirmation()/
# fail_pending_confirmation()) - unlike action_name/resource_key above,
# this value is never generated by this call's own caller; it is
# code-generated once at propose_confirmation() time (see generate_task_id())
# and handed back by whatever external caller is approving/denying later
# (Milestone 46's eventual WhatsApp reply routing, in a future milestone -
# not this one). Sized with generous headroom over a UUID7 string's fixed
# 36 characters - this bound intentionally does NOT require confirmation_id
# to look like a UUID (see generate_task_id()'s own "opaque, code-generated"
# framing): exact opaque-token matching is what actually authorizes
# anything, never a specific string shape.
MAX_CONFIRMATION_ID_CHARS = 128

DISPLAY_ID_PREFIX = "TASK-"
DISPLAY_ID_LENGTH = 8
# Bounded retry count for the extremely unlikely case that a freshly
# generated display_id (or, vanishingly less likely, task_id) collides
# with an existing row's UNIQUE constraint - see generate_display_id()'s
# docstring and TaskRepository.create_task().
MAX_DISPLAY_ID_ATTEMPTS = 5

MIN_LIST_LIMIT = 1
MAX_LIST_LIMIT = 100
DEFAULT_LIST_LIMIT = 20

# Crockford-style uppercase alphabet with visually ambiguous characters
# (0, 1, I, L, O) removed - safe to read aloud or copy from a WhatsApp
# message without misreading a character.
_DISPLAY_ID_ALPHABET = "23456789ABCDEFGHJKMNPQRSTUVWXYZ"


class TaskState(str, Enum):
    """The closed set of lifecycle states a persisted task may be in.
    Inherits str so a TaskState member compares equal to, and can be
    stored/read as, its plain string value - no separate serialization
    step is needed at the SQLite boundary."""

    CREATED = "created"
    PLANNING = "planning"
    READY = "ready"
    RUNNING = "running"
    WAITING_FOR_CONFIRMATION = "waiting_for_confirmation"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


# Terminal states never accept a further transition, including back to
# themselves or to another active state - enforced both here (in
# TaskRepository, before any SQL runs) and structurally, since none of
# them appear as a key with a non-empty value in ALLOWED_TRANSITIONS.
TERMINAL_STATES = frozenset({TaskState.COMPLETED, TaskState.FAILED, TaskState.CANCELLED})

# The exact, closed transition table. Cancellation is allowed from every
# non-terminal state - nothing in the current roadmap needs an
# uncancellable working state. No other states or edges exist.
ALLOWED_TRANSITIONS: dict[TaskState, frozenset[TaskState]] = {
    TaskState.CREATED: frozenset({TaskState.PLANNING, TaskState.CANCELLED, TaskState.FAILED}),
    TaskState.PLANNING: frozenset({TaskState.READY, TaskState.CANCELLED, TaskState.FAILED}),
    TaskState.READY: frozenset({TaskState.RUNNING, TaskState.CANCELLED, TaskState.FAILED}),
    TaskState.RUNNING: frozenset(
        {
            TaskState.WAITING_FOR_CONFIRMATION,
            TaskState.COMPLETED,
            TaskState.FAILED,
            TaskState.CANCELLED,
        }
    ),
    TaskState.WAITING_FOR_CONFIRMATION: frozenset(
        {TaskState.RUNNING, TaskState.CANCELLED, TaskState.FAILED}
    ),
    TaskState.COMPLETED: frozenset(),
    TaskState.FAILED: frozenset(),
    TaskState.CANCELLED: frozenset(),
}


class StepStatus(str, Enum):
    """The closed set of durable statuses one plan step's progress row may
    hold (Milestone 42 P1). Inherits str for the same reason
    TaskState does - a member compares equal to, and can be stored/read
    as, its plain string value.

    There is deliberately no NOT_STARTED member: the absence of a
    task_step_progress row for a given (task_id, step_position) IS
    "not started" - see TaskRepository.claim_step()/get_step_progress().
    Persisting an explicit not_started row for every step of every plan
    would be redundant data with no independent meaning."""

    IN_PROGRESS = "in_progress"
    SUCCEEDED = "succeeded"
    FAILED = "failed"


# Write-once terminal step statuses (SUCCEEDED, FAILED) are enforced
# directly by TaskRepository._finalize_step()'s conditional UPDATE
# (... WHERE status = 'in_progress') - unlike TERMINAL_STATES, no separate
# frozenset constant is declared here, since nothing in this package needs
# to test "is this status terminal" as a standalone question; the one
# place that matters (_finalize_step()) already expresses the equivalent
# and sufficient condition ("is this status still in_progress") directly
# in SQL.


class TaskStorageError(Exception):
    """Base class for every error kernel/employee_tasks/ raises
    deliberately (as opposed to letting an unrelated exception escape).
    Never carries a SQL fragment, stack trace, or raw driver exception
    text meant for a caller to inspect via str() - callers select a
    fixed, safe message by exception *type*, matching
    kernel/knowledge_base/types.py's own convention."""


class TaskNotFoundError(TaskStorageError):
    """No task exists with the given task_id or display_id."""


class InvalidTransitionError(TaskStorageError):
    """The requested expected_state -> new_state pair is not in
    ALLOWED_TRANSITIONS, new_state is not a recognized TaskState, or the
    task's actual current state no longer matches the caller's
    expected_state (a stale write, including one lost to a concurrent
    writer). Neither the tasks row nor the journal is ever modified when
    this is raised."""


class TaskAlreadyTerminalError(TaskStorageError):
    """The task's actual current state is already terminal
    (completed/failed/cancelled). Distinct from InvalidTransitionError so
    a caller can tell "you tried to skip/reverse a step" apart from "this
    task is already done and cannot be touched again"."""


class DuplicateTaskError(TaskStorageError):
    """create_task() was called with a dedup_key that already exists."""


class TaskStorageUnavailableError(TaskStorageError):
    """The task database file or its containing directory could not be
    opened, created, initialized, or written to (including a write lock
    that could not be acquired within the busy timeout)."""


class TaskStorageCorruptError(TaskStorageError):
    """The database's persisted content is not what this code itself
    ever writes - either PRAGMA integrity_check reported an actual
    inconsistency in the database file (see db.py's check_integrity()),
    or (Milestone 42 P2) a persisted, code-generated timestamp column
    (e.g. task_pending_confirmation.expires_at) failed to parse back as a
    timezone-aware datetime (see parse_task_timestamp() below) - both are
    the same underlying concern: this layer's own prior write does not
    match what this layer expects to read back. Distinct from a schema
    version mismatch (TaskSchemaIncompatibleError), which is a perfectly
    readable file written by, or intended for, a different schema
    version."""


class TaskSchemaIncompatibleError(TaskStorageError):
    """The database's schema_meta.schema_version does not match the
    version this code expects."""


class TaskInputTooLargeError(TaskStorageError):
    """An externally supplied field violates this layer's bounded-input
    contract: the wrong type, too short, too long, or containing an
    embedded NUL byte - or, for metadata_json specifically, not
    syntactically valid JSON text. Named for the most common case (an
    oversized field) but covers the whole bounded-input contract, so the
    error taxonomy stays closed rather than growing one class per
    validation rule."""


class StepAlreadyClaimedError(TaskStorageError):
    """TaskRepository.claim_step() targeted a (task_id, step_position)
    pair that already has a task_step_progress row - whatever its status.
    A step may be claimed exactly once: the underlying INSERT relies on
    the table's (task_id, step_position) PRIMARY KEY to guarantee that,
    of any number of concurrent callers claiming the same step, exactly
    one succeeds and every other one gets this error. Never retried
    automatically - see kernel/task_execution/ (Milestone 42) for the
    fail-closed policy this supports."""


class StepNotInProgressError(TaskStorageError):
    """TaskRepository.mark_step_succeeded()/mark_step_failed() was called
    for a (task_id, step_position) that either has no claimed row at all,
    or whose row is no longer in_progress (already succeeded or failed).
    Terminal step status is write-once: neither a succeeded nor a failed
    row can ever move to any other status, and a terminal row's
    result/failure fields can never be overwritten - both are enforced by
    this same error, raised from the same conditional-UPDATE guard."""


class NoPendingConfirmationError(TaskStorageError):
    """No task_pending_confirmation row exists for the given task_id -
    raised by consume_confirmation_and_claim_step()/deny_confirmation()
    when there is nothing to approve/deny (including a second attempt
    after the first already consumed or denied it)."""


class ConfirmationMismatchError(TaskStorageError):
    """The confirmation identity supplied to
    consume_confirmation_and_claim_step()/deny_confirmation() does not
    EXACTLY match the currently pending task_pending_confirmation row
    (confirmation_id and, for approval, step_position/action_name/
    resource_key too). Never partially honored - a mismatch on any single
    field fails the whole call closed, exactly like a stale or replayed
    confirmation_id must never be treated as authorizing a different,
    newer pending confirmation for the same task."""


class ConfirmationExpiredError(TaskStorageError):
    """The pending confirmation matched exactly, but its expires_at has
    already passed. consume_confirmation_and_claim_step() raises this
    without mutating anything - the caller (kernel/task_execution/) is
    expected to call fail_pending_confirmation() as a separate, explicit
    step to actually transition the task to failed; this error alone
    never does that itself, so an attempted approve never has a silent
    side effect beyond reporting why it did not succeed."""


@dataclass(frozen=True)
class TaskRecord:
    """One persisted task's current row. `metadata_json` and `plan_json`
    are both stored and returned as opaque, size-capped JSON strings -
    this layer never parses their keys or acts on their contents (see
    repository.py). `plan_json` is None until a validated plan has been
    persisted (schema version 2, Milestone 41 P2) - only
    TaskRepository.persist_plan_and_ready() ever sets it, exactly once,
    atomically with the planning -> ready transition; there is no general
    update API for it."""

    task_id: str
    display_id: str
    state: TaskState
    request_text: str
    source: str
    dedup_key: str | None
    created_at: str
    updated_at: str
    started_at: str | None
    completed_at: str | None
    failure_code: str | None
    failure_summary: str | None
    metadata_json: str
    protocol_version: int
    version: int
    plan_json: str | None = None


@dataclass(frozen=True)
class TaskTransition:
    """One append-only journal row. `from_state` is None only for the
    synthetic creation event (see TaskRepository.create_task) - every
    later transition always has both a from_state and a to_state."""

    transition_id: int
    task_id: str
    from_state: TaskState | None
    to_state: TaskState
    timestamp: str
    reason_code: str | None
    safe_summary: str | None
    task_version: int


@dataclass(frozen=True)
class TaskStepProgress:
    """One durable task_step_progress row (Milestone 42 P1) - the
    smallest durable record of one plan step's execution progress.
    `step_position` matches kernel.task_planner.types.PlanStep.position
    exactly, but this layer never imports or inspects PlanStep/TaskPlan -
    step_position is treated as an opaque, positive, code-supplied integer,
    exactly like plan_json's content is opaque to this package (see
    kernel/employee_tasks/__init__.py's own scope statement).

    There is no row for a step that has not been claimed yet - see
    StepStatus's own docstring. `result_json` is populated only once the
    step reaches a terminal status (`succeeded`, always; `failed`,
    optionally) and is treated exactly as opaquely as plan_json/
    metadata_json: this layer validates only that it parses as JSON and
    stays within its size bound. `task_version` is the `tasks.version`
    value observed at claim time - a lightweight forensic snapshot, not a
    concurrency mechanism in its own right (the (task_id, step_position)
    PRIMARY KEY is what actually makes claim_step() atomic)."""

    task_id: str
    step_position: int
    status: StepStatus
    started_at: str
    completed_at: str | None
    result_json: str | None
    failure_code: str | None
    failure_summary: str | None
    task_version: int


@dataclass(frozen=True)
class PendingTaskConfirmation:
    """One durable task_pending_confirmation row (Milestone 42 P2) - a
    task-scoped, durable pending confirmation, wholly independent of
    kernel/tools/confirmation.py's in-memory, single-slot ConfirmationStore
    (which remains untouched and keeps serving the existing ad hoc
    `/task ...` command path).

    `task_id` is the PRIMARY KEY: the architecture guarantees at most one
    pending confirmation per task, since execution is strictly sequential
    (a task can only be RUNNING one step's worth of work, or
    WAITING_FOR_CONFIRMATION for exactly one proposed step, at a time).
    `confirmation_id` is a separate, code-generated, single-use identity
    token - NOT the same value as task_id - because task_id alone cannot
    distinguish "the confirmation currently pending" from "a different,
    later confirmation this task will eventually propose after this one
    is resolved": approval/denial must match confirmation_id exactly, so a
    stale or replayed confirmation_id can never be mistaken for a newer,
    unrelated proposal. `step_position`/`action_name`/`resource_key`
    identify EXACTLY which persisted plan step/action/resource was
    proposed - snapshotted at propose time, never re-derived later.

    THREAT BOUNDARY (Milestone 42 P2 correction): approve_task_confirmation()
    (kernel/task_execution/service.py) re-binds this row's step_position to
    the immutable persisted TaskPlan and verifies action_name/resource_key
    match the resolved PlanStep exactly - this defeats a partial tamper
    (any ONE of these three fields changed in isolation, whether by an
    application bug, a race, or partial/corrupt mutation) by making the
    mismatch detectable. It does NOT, and is not intended to, defeat a
    coordinated rewrite by an attacker with arbitrary direct SQLite write
    access who changes ALL THREE fields together to exactly describe a
    DIFFERENT, currently-valid ACTION step already present in the SAME
    persisted plan - the database holds no independent, tamper-evident
    record of the original proposal to detect that specific rewrite
    against. This is a deliberate scope boundary, not an oversight: M42's
    threat model is stale/corrupt/inconsistent persisted state,
    application-level races, accidental partial mutation, replay, and
    unauthorized substitution by models or runtime code - never
    cryptographic tamper-resistance against an attacker who already has
    arbitrary write access to this process's own SQLite file (an
    attacker at that privilege level could equally rewrite tasks.plan_json
    itself, or any other row in this database). Defending against that
    specific threat would require an independent trust boundary (e.g. an
    authenticated/signed proposal record, or storage this process does not
    itself have unrestricted write access to) that no part of this
    codebase's existing threat model calls for today."""

    task_id: str
    confirmation_id: str
    step_position: int
    action_name: str
    resource_key: str | None
    created_at: str
    expires_at: str


def parse_task_timestamp(value: str, field_name: str = "timestamp") -> datetime:
    """Parse a code-generated ISO-8601 timestamp this package itself wrote
    (e.g. PendingTaskConfirmation.expires_at) back into a real,
    timezone-aware datetime - for any chronological comparison (in
    particular an authorization-expiry decision - see
    TaskRepository.consume_confirmation_and_claim_step()), never a lexical
    string comparison. Two ISO-8601 strings sharing the exact same
    formatting convention usually happen to sort correctly as plain
    strings, but nothing here should ever depend on that coincidence
    holding for every representable instant - datetime.isoformat() omits
    the fractional-seconds component entirely when it is exactly zero,
    which is exactly the kind of formatting variation string comparison
    must not be trusted to handle correctly, security-relevant or not.

    A value that fails to parse, or parses as timezone-naive, is a
    storage/integrity concern - this package never itself writes such a
    value - so it fails closed as TaskStorageCorruptError, never silently
    treated as a valid (and in particular never as a "not yet expired")
    timestamp. Shared by kernel.employee_tasks.repository and
    kernel.task_execution.service so neither package maintains its own,
    possibly-drifting copy of this parsing/validation logic."""

    if not isinstance(value, str):
        raise TaskStorageCorruptError(f"{field_name} must be a string")
    try:
        parsed = datetime.fromisoformat(value)
    except ValueError as exc:
        raise TaskStorageCorruptError(f"{field_name} is not a valid ISO-8601 timestamp") from exc
    if parsed.tzinfo is None:
        raise TaskStorageCorruptError(f"{field_name} is not a timezone-aware timestamp")
    return parsed


def generate_task_id() -> str:
    """Code-generated, time-ordered (UUID7), globally-unique-enough-for-
    one-installation task identity. Never derived from, or influenced by,
    model output - see kernel/employee_tasks/__init__.py."""

    return str(uuid.uuid7())


def generate_display_id(task_id: str) -> str:
    """Deterministic short code derived from task_id's raw bytes - not an
    independent random draw, so there is nothing extra to generate,
    persist, or reconcile against task_id itself.

    Algorithm: interpret the UUID's 128 bits as one big-endian integer,
    then repeatedly divmod by len(_DISPLAY_ID_ALPHABET), taking
    DISPLAY_ID_LENGTH digits least-significant-first and reversing them
    at the end - i.e. this is exactly "encode the integer in base 31
    using this alphabet, keep the last 8 digits". Prefixed with
    DISPLAY_ID_PREFIX ("TASK-") for readability.

    This is a *lossy* projection of 128 bits down to 8 symbols from a
    31-character alphabet (~40 bits) - collisions between two different
    task_ids are possible in principle (roughly 1 in 31**8), which is
    exactly why TaskRepository.create_task() treats a display_id UNIQUE
    violation as a signal to retry with a fresh task_id/display_id pair
    (bounded by MAX_DISPLAY_ID_ATTEMPTS) rather than assuming this
    function is injective. Not a secret, and never used for
    authorization - see kernel/employee_tasks/__init__.py.
    """

    raw = uuid.UUID(task_id).bytes
    remaining = int.from_bytes(raw, "big")
    base = len(_DISPLAY_ID_ALPHABET)
    digits = []
    for _ in range(DISPLAY_ID_LENGTH):
        remaining, remainder = divmod(remaining, base)
        digits.append(_DISPLAY_ID_ALPHABET[remainder])
    return DISPLAY_ID_PREFIX + "".join(reversed(digits))
